# Generated by Django 5.0.8 on 2025-04-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='You have applied for account please wait for verification process', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of account', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this bank active? only active accounts will be available for withdrawal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=50, unique=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=3, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fee_amount', models.FloatField(default=0)),
                ('fee_type', models.CharField(choices=[('product_listing_fee', 'Product Listing Fee'), ('transaction_fee', 'Transaction Fee'), ('payment_processing', 'Payment Processing Fee'), ('deposit_fee', 'Deposit Fee'), ('currency_conversion', 'Currency Conversion Fee'), ('vat_processing', 'VAT on Processing Fees'), ('vat_seller_services', 'VAT on Seller Services')], max_length=30)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('init', 'Initialized'), ('pending', 'Pending'), ('completed', 'Completed')], default='init', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayPalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='You have applied for account please wait for verification process', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of account', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this bank active? only active accounts will be available for withdrawal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Paypal Accounts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('charge', 'Charge'), ('refund', 'Refund')], default='deposit', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_account_country', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_account_email', models.EmailField(max_length=254, null=True)),
                ('stripe_description', models.JSONField(blank=True, null=True)),
                ('stripe_is_active', models.BooleanField(default=False)),
                ('total_amounts', models.FloatField(default=0)),
                ('total_deposits', models.FloatField(default=0)),
                ('total_earnings', models.FloatField(default=0)),
                ('total_withdrawals', models.FloatField(default=0)),
                ('balance_available', models.FloatField(default=0)),
                ('balance_pending', models.FloatField(default=0)),
                ('outstanding_charges', models.FloatField(default=0)),
                ('connect_available_balance', models.FloatField(default=0)),
                ('connect_available_balance_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('connect_pending_balance', models.FloatField(default=0)),
                ('connect_pending_balance_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Wallets',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('withdrawal_type', models.CharField(choices=[('bank', 'Bank'), ('connect', 'Connect')], default='bank', max_length=20)),
                ('description', models.TextField(blank=True, help_text='You have applied for account please wait for verification process', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of withdrawal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
