# Generated by Django 5.0.8 on 2025-04-17 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('user', 'User'), ('service', 'Service')], default='user', help_text="The type of report: either 'User' or 'Service'.", max_length=20)),
                ('reason', models.TextField(help_text='The reason for reporting. Provide as much detail as possible.')),
                ('additional_info', models.TextField(blank=True, help_text='Optional additional information about the report.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the report was created.')),
                ('is_resolved', models.BooleanField(default=False, help_text='Indicates whether the report has been resolved.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='The date and time when the report was resolved.', null=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
