# Generated by Django 5.0.8 on 2025-04-18 03:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='certifications-lol/')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience (0-50)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('image', models.ImageField(blank=True, upload_to='agent-profile-images/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='profiles-cover/')),
                ('skills', models.TextField(help_text='Describe your specialties (e.g., Tour guide, Visa expert)')),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('certifications', models.ManyToManyField(blank=True, to='local_guide.certification')),
                ('languages_spoken', models.ManyToManyField(blank=True, to='local_guide.language')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the place', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the place')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the place', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the place', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('category', models.CharField(choices=[('TOURIST_ATTRACTION', 'Tourist Attraction'), ('HISTORICAL_SITE', 'Historical Site'), ('NATURAL_LANDMARK', 'Natural Landmark'), ('CULTURAL_SITE', 'Cultural Site'), ('ADVENTURE', 'Adventure Spot'), ('OTHER', 'Other')], default='TOURIST_ATTRACTION', help_text='Category of the place', max_length=50)),
                ('address', models.CharField(blank=True, help_text='Physical address of the place', max_length=255)),
                ('contact_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('website', models.URLField(blank=True, help_text='Official website')),
                ('operating_hours', models.TextField(blank=True, help_text='Operating hours (e.g., Mon-Fri: 9 AM - 5 PM)')),
                ('accessibility_info', models.TextField(blank=True, help_text='Accessibility details')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0.0 to 5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the place is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_guide', models.ForeignKey(blank=True, help_text='Agency managing or associated with this place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='local_guide.agentprofile')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='AgentOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.CharField(help_text='e.g., Tour Guide, Interpreter, Personal Shopper', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='local_guide.agentprofile')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_offers', to='local_guide.place')),
            ],
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['full_name'], name='local_guide_full_na_6f7b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='local_guide_name_09dcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category'], name='local_guide_categor_613ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='agentoffer',
            index=models.Index(fields=['title'], name='local_guide_title_14957d_idx'),
        ),
    ]
